### ISSUE TITLE
Encrypted Backups?

### ISSUE THREAD

**Issue by dm17** [weseek/mongodb-awesome-backup#20]
Is there a way to encrypt before backup? Or is that out of scope?
Thanks.

**Comment by skomma** [comment]
Thank you for creating an issue.

We're sorry, we don't plan to implement such a feature right now.
But for our reference, could you tell us the way or the command to encrypt you are going to perform.

**Comment by dm17** [comment]
Just going to encrypt the stuff on the system with a password or key before sending it to the remote servers... Seems a lot safer. Not sure how I will yet.

**Comment by ryu-sato** [comment]
@dm17 Because backup file cannot be read following reasons, many cases in a safe.

1. In mab container, temporary file created by mongodump will be removed after backup.
    * When mab is executed in non cron mode, the file is removed with the container. (You should set `--rm` option executing mab)
    * When mab is executed in cron mode, the file is removed after backup. (ref. https://github.com/weseek/mongodb-awesome-backup/blob/55449cbf5bb89454eece647b1820255ac19a2c58/bin/backup.sh#L77-L81)

2. Uploading backup file is encrypted.
    * Google Cloud CLI (gsutil) use HTTPS. (see: https://stackoverflow.com/questions/50764722/is-gsutil-cp-secure-for-uloading-sensitive-data)
        > By default, gsutil accesses Cloud Storage through JSON API request endpoints. You can change this default to the XML API.
        > The JSON API request endpoint is HTTPS - so assuming the security provided by HTTPS is sufficient for your needs, it should be fine. That won't guard against attacks if your local machine has been compromised with a bogus version of gsutil, but at that point all bets are probably off.
    * aws CLI (aws) use SSL. (see: https://docs.aws.amazon.com/cli/latest/reference/)
        > By default, the AWS CLI uses SSL when communicating with AWS services. For each SSL connection, the AWS CLI will verify SSL certificates. This option overrides the default behavior of verifying SSL certificates.

3. S3 and GCS can control access to stored files. (Also encrypting can be enabled)
    * GCS encrypt files as default. (ref. https://cloud.google.com/storage/docs/encryption)
    * aws can encrypt files, but mab cannot use this feature. (ref: https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html)

If the reason is not enough, could you tell me details.

**Comment by ryu-sato** [comment]
Close because no discussions.
