### ISSUE TITLE
Support for custom s3 endpoints

### ISSUE THREAD

**Issue by pitscher** [weseek/mongodb-awesome-backup#27]
Hi there,
thank you for this tool. I use it in a few live systems and it's all fine.
But adding support for s3 based services like DigitalOcean Spaces would be nice.
(Not everyone uses AWS or GCP)

If you think this is useful I will create a PR. :)

**Comment by ryu-sato** [comment]
We think, too.
PR is always welcome! :)

**Comment by pitscher** [comment]
Issue closed because mentioned changes are now merged.
